name: Deploy

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    DEPLOY_BRANCH: gh-pages
    DEPLOY_DIR: dist
    GIT_CONFIG_NAME: "[Automated] Yui"
    GIT_CONFIG_EMAIL: yukino-org@users.noreply.github.com
    GIT_COMMIT_MSG: "[automated] deploy site (${{ github.sha }})"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 14.x
                  cache: yarn

            - uses: actions/setup-python@v2
              with:
                  python-version: 3.x

            - name: 🚧 Install dependencies
              run: |
                  yarn
                  yarn setup

            - name: 👷 Build site
              run: yarn build

            - name: 🚀 Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: ${{ env.DEPLOY_BRANCH }}
                  folder: ${{ env.DEPLOY_DIR }}
                  commit-message: ${{ env.GIT_COMMIT_MSG }}
                  git-config-name: ${{ env.GIT_CONFIG_NAME }}
                  git-config-email: ${{ env.GIT_CONFIG_EMAIL }}
